### ISSUE TITLE
docker image on dockerhub doesn't contain readonly option

### ISSUE THREAD

**Issue by rhetr** [pldubouilh/gossa#60]
for some reason when I try to pull gossa from dockerhub, the /start.sh script doesn't have the `-ro=${READONLY}` option and I have to manually edit and restart the container. when I built a container from scratch and I didn't have this issue.

```
---
version: '3.7'

services:
  gossa:
    image: pldubouilh/gossa
    container_name: gossa
    environment:
      - READONLY=true
    volumes:
      - /mnt/media:/shared
    ports:
      - 8001:8001
    restart: unless-stopped
```
